// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SocialConnect.Core.Entities;

public class UserRole : IdentityRole
{
    public string NormalUser { get; set; }
    public User User { get; set; }

    public bool Admin { get; set; }

    public bool Reader { get; set; }

    public bool Editor { get; set; }

}